import builder from 'focus-core/util/url/builder';
import {getConfig} from '../../config';

const url = getConfig().API_ROOT;
export default {
    createNews:  builder(url + 'news', 'PUT'),
    loadAllNews:  builder(url + 'news', 'GET'),
    markNewsAsRead:  builder(url + 'markNewsAsRead/${id}', 'GET'),
    editNews:  builder(url + 'news/${id}', 'POST'),
    deleteNews:  builder(url + 'news/${id}', 'DELETE'),
    loadAllUsers: builder(url + 'users', 'POST'),
    loadAllUsersCount: builder(url + 'usersCount', 'POST'),
    loadAllActiveUsers: builder(url + 'usersActifs', 'POST'),
    exportAllUsers: builder(url + 'usersExport', 'POST'),
    exportAllEvents: builder(url + 'eventExport', 'POST'),
    canCreateToggle:  builder(url + 'toggleCreation/${id}', 'POST'),
    toggleAdmin:  builder(url + 'toggleAdmin/${id}', 'POST'),
    toggleActif: builder(url + 'toggleActif/${id}', 'POST'),
    updateUser: builder(url + 'updateUser/${id}', 'POST'),
    editPartenaire:  builder(url + 'partenaires/${id}', 'POST'),
    deletePartenaire:  builder(url + 'partenaires/${id}', 'DELETE'),
    createPartenaire:  builder(url + 'partenaires', 'PUT'),
    editEntreprise:  builder(url + 'entreprise/${id}', 'POST'),
    deleteEntreprise:  builder(url + 'entreprise/${id}', 'DELETE'),
    createEntreprise:  builder(url + 'entreprise', 'PUT'),
    loadUsersForMail:  builder(url + 'loadUsersForMail', 'GET'),
    editPresentation:  builder(url + 'presentations/${id}', 'POST'),
    deletePresentation:  builder(url + 'presentations/${id}', 'DELETE'),
    createPresentation:  builder(url + 'presentations', 'PUT'),
    editTypeEvenement:  builder(url + 'typeEvenements/${id}', 'POST'),
    deleteTypeEvenement:  builder(url + 'typeEvenements/${id}', 'DELETE'),
    createTypeEvenement:  builder(url + 'typeEvenements', 'PUT'),
    loadAllRibbons: builder(url + 'ribbons', 'GET'),
    editRibbon:  builder(url + 'ribbons/${id}', 'POST'),
    deleteRibbon:  builder(url + 'ribbons/${id}', 'DELETE'),
    createRibbon:  builder(url + 'ribbons', 'PUT'),
    loadUserRibbons:  builder(url + 'getRibbons/${id}', 'POST'),
    toggleRibbon: builder(url + 'toggleAddRibbon/${usrId}/${ribId}', 'POST'),
    toggleActiveRibbon: builder(url + 'toggleActifRibbon/${ribId}', 'POST'),
    allBlocs: builder(url + 'allBlocs', 'GET'),
    saveBloc: builder(url + 'saveBloc/${id}', 'POST'),
    allBadges: builder(url + 'allBadges', 'GET'),
    saveBadges: builder(url + 'saveBadges', 'POST'),
    editMedia:  builder(url + 'medias/${id}', 'POST'),
    deleteMedia:  builder(url + 'medias/${id}', 'DELETE'),
    createMedia:  builder(url + 'medias', 'PUT'),
    editMachine:  builder(url + 'machines/${id}', 'POST'),
    deleteMachine:  builder(url + 'machines/${id}', 'DELETE'),
    createMachine:  builder(url + 'machines', 'PUT'),
    editDayOff:  builder(url + 'dayOffs/${id}', 'POST'),
    deleteDayOff:  builder(url + 'dayOffs/${id}', 'DELETE'),
    createDayOff:  builder(url + 'dayOffs', 'PUT'),
    toggleChat: builder(url + 'toggleChat/${id}', 'POST'),
    listFiles: builder(url + 'listFile', 'GET')
};
